In [78]:
import pandas as pd

# Specify the file path
file_path = "../../data/translated_comments.xlsx"

# Load the Excel file into a DataFrame
df = pd.read_excel(file_path)

In [79]:
# Load a specific sheet named 'Sheet1'
df = pd.read_excel(file_path, sheet_name='Sheet1')

In [80]:
df.head()

            Comment Id                            Comment
0  7221188022045099008                     rashmika වාසිය
1  7221178613064123392                  rashmika වෙගී ade
2  7221176459355882496                              සාරංග
3  7333542921793094656              ඉස්සරහට නිලියක් ශුවර්
4  7221231966270751744  rashmika මතකේ una..eya වාසිය ටිකක

In [81]:
# Get the row count
row_count = df.shape[0]

print("Row count of the DataFrame:", row_count)

Row count of the DataFrame: 14017

In [5]:
# Find null values in the "Comment" column
null_comments = df[df['Comment'].isnull()]

# Display null values in the "Comment" column
print("Null values in the 'Comment' column:")
print(null_comments)

Null values in the 'Comment' column:
                Comment Id Comment
44     7221177654576825344     NaN
45     7221176223815713792     NaN
48     7243025175670604800     NaN
50     7224778042249839616     NaN
52     7223030238438032384     NaN
...                    ...     ...
13813  7304609734580945920     NaN
13814  7301703176813511680     NaN
13815  7294979703093068800     NaN
13816  7294296586959471616     NaN
13890  7292693117953934336     NaN

[3122 rows x 2 columns]

In [6]:
# Drop rows with null values in the "Comment" column
df = df.dropna(subset=['Comment'])

In [7]:
# Get the row count
row_count = df.shape[0]

print("Row count of the DataFrame:", row_count)

Row count of the DataFrame: 10895

In [8]:
# Specify the file path for the new file
output_file_path = "../../data/finale_dataset_v1.xlsx"

# Save the DataFrame to a new Excel file
df.to_excel(output_file_path, index=False)

print("DataFrame saved to", output_file_path)

DataFrame saved to ../../data/finale_dataset_v1.xlsx

## Starting the BERT model fine tune for the dataset

In [9]:
pip install transformers datasets

Requirement already satisfied: transformers in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (4.42.3)
Requirement already satisfied: datasets in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (2.18.0)
Requirement already satisfied: filelock in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (3.13.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (0.23.4)
Requirement already satisfied: numpy<2.0,>=1.17 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (1.26.3)
Requirement already satisfied: packaging>=20.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (2023.12.25)
Requirement already satisfied: requests in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (2.31.0)
Requirement already satisfied: safetensors>=0.4.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (0.4.2)
Requirement already satisfied: tokenizers<0.20,>=0.19 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (4.66.2)
Requirement already satisfied: pyarrow>=12.0.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (15.0.2)
Requirement already satisfied: pyarrow-hotfix in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (2.1.4)
Requirement already satisfied: xxhash in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.2.0,>=2023.1.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from fsspec[http]<=2024.2.0,>=2023.1.0->datasets) (2024.2.0)
Requirement already satisfied: aiohttp in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (3.9.3)
Requirement already satisfied: aiosignal>=1.1.2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.10.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (2023.11.17)
Requirement already satisfied: colorama in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: six>=1.5 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

# Specify the file path
file_path = "../../data/mnt/sentiment_Aspect_added.xlsx"

# Load the Excel file into a DataFrame
df = pd.read_excel(file_path)

In [3]:
df.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset

# Load the dataset
file_path = '../../data/mnt/sentiment_Aspect_added.xlsx'
data = pd.read_excel(file_path)

# Split the dataset into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

# Convert pandas dataframes to Hugging Face datasets
train_dataset = Dataset.from_pandas(train_data)
test_dataset = Dataset.from_pandas(test_data)

# Verify the split
print(f"Training set size: {len(train_dataset)}")
print(f"Testing set size: {len(test_dataset)}")

Training set size: 568
Testing set size: 142

In [5]:
# Ensure the column name is correct
assert 'Comment' in data.columns, "Column 'Comment' not found in the dataset."

In [6]:
data.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

In [7]:
data['Comment'].head()

0                        rashmika වගේ
1                   rashmika වෙගේ අඩේ
2                               සාරංග
3               ඉස්සරහට නිලියක් ශුවර්
4    rashmika මතක් උනා. එයා වගේ ටිකක්
Name: Comment, dtype: object

In [8]:
comments = data['Comment'].tolist()  # Ensure it's a list of strings
for comment in comments:
    print(comment)

rashmika වගේ
rashmika වෙගේ අඩේ
සාරංග
ඉස්සරහට නිලියක් ශුවර්
rashmika මතක් උනා. එයා වගේ ටිකක්
ව්‍යාකූල උනා පිපිරීම මීට සාරන්ග
මේ අර සිකුරු ඇවිත් ට්‍රාමා එකේ අන්ජලී නේද?
එයා නම් ලස්සනයි
She is ලස්සන
rashmika මඳන වාගී
අනවශ්‍ය තොරතුරක්...
සාරංග වම
ආහ... අනවශ්‍ය තොරතුරක් ..
සාරංගයා
සාරංග ලෙෆ්ට්
වාව් රශ්මිකා වගේ
nan
@
මෙ වගෙ නිලියක් ඉන්නො නෙඩ
සාරාංග
@Navee කෙල්ල මේ අර එදාඅ කිවුවේ
ප් රතික් රියාව එක උගේ
සාරංග ව් යාකූලත්වය
සාරංග මරැ
Hayyo සාරංග
rashmika වාසිය
rashmika වාසිය
adeh සිරාවටම අහේ awlakda rashmika වාගෙනෙ
@Dinakshie Saranga Dina හොයමින් සුන්දර
She's සුන්දර
අම්මොහ් සාරංග
just හරියට mandana....
rashmikage හිනාව මයි
ව් යාකූලත්වය උනා සාරංග
සාරංග
එයාගේ තව නැද්ද
rashmika මඳන vage...
rashmika වාසිය
සාරංග අයියා
Tikak Rashmika වාගී
බලන්න හරියට a rashmika @iamrashmika
බලන්න හරියට rashmika
The few momments පස්සෙ
rashmika
rasmika wagemi
රශ්මිකා වගේ එයා
දෙරණ ඩ්‍රාමා එකක මෙයා ඇක්ට් කරනවා නේද
ලස්සන
@anjaliwathsalajayasinghe
@Dinakshie Saranga අයියගේ මූණ
ව් යාකූලත්වය
සාරංග අයියා
Anjale අක්ක
tr@Trading මිනිසා
හෝරා ගෙදිය
සාරංග
සාරංග
මේ විනිශ්‍ය මණ්ඩලය බලන්නකෝ.
Saranga
සාරංග අයියගේ මුණා
sheshadri වෙගී ටිකක
සාරංග
සාරංග
අපේ වසිකිලිය බලාන්න එන්නකෝ Saaranga අයියේ
Rashmika
සාරංග
දැන් චීනෙට ගියපුවම නම වෙනස් වෙනවද අපේ
අංජලි සිකුරුඇවිත්
අන්ජලී තත්පරය
සාරංග
Rashmikada mandaaah
සාරංග අයියා
අඩෝ සාරංග
සාරංග
සාරංග අයියා
Saranga comfused ඌනා බෑග්
aWZwaW
@~ PaMoD මෙකෙන් මන් දැනගත්තෙ
rashmika මඳන වාසිය
ශ් රී ලංකා ලංකන් rashmika
rashmika වගේ
rashmika වගේ
rashmika වගේ
rashmika වගේ
rashmika මන්දන්නෙ වගේ
rashmika වගේ
Rashmika inenaaa!!
rashmika වගේ
rashmika වගේ
වාල තත්ත්වය ඒකාට ගහණන් බෑහ් ඉතින් වෙබ් phones waltdanno daniti
හෝ ඇපල් ෆෑන්ස්ලා ටිපර් වේවි
fingerprind unlock=touch ID මුහුණ unlock=face ID වැඩි refreshrate=promotion Ram=unified මතකය තවත්් උදාහරන
Samsung නැඩ ඇපල් දර්ශකය ඇක ගැහෙන්නෙ
1 4pro max එකක් ගත්ත විතරයි යකෝ
samsung හඳ ෆොටෝ faking සටහන ඇක ගණා යාවත් කාළීන: ඇක්–ඇක් දාපනේ අතල ඒකාට වාසිය
අයියේ ටිකා ටොක් වාල වාසිය උපක් රමය ගේන්නකො
මැක් පොතpage 13 අඟල් එස දර්ශකය ඒකයි 14 අඟල් දර්ශකය ඇක ඔ්‍යා kathawamada වෙනසක නෑද්ද
USA BRANDING TRICKS
චාලික දුපත
චාලික දුපත
MTFE ජාන ඕනි
Menna කංචුක
ඇපල් users:- අයියෝ samiii
ගේමු
Macbook දර්ශකය එක ඇත්තටම හොදයි. ඒත් තිරය කතාව මේකම තමයි
අත්තක
chatgp එක්
Mn ගවා තියෙන්නෙ I දුරකථනය 12 ekak. Eka වෙළඳාම in කරනනා එක් Mata I දුරකථනය 14 ප් රොජෙක් max ඒකකට ඇපල් වෙළඳසැල් eken. Ehema කරාන ඇක වටිනාකම da? කරුණාකරලා උදව්
විකී ඔ්‍යා ඇපල් එප කරවෙනවා
Appleලගේ සංදර්ශකය හදන්නෙත් Samsung, Lgලා නේත
interesting..Name නව යොදාගැනීම
පද්ධතිය සකස්නය කරන නිසා තමා iphone හොද
ඇපල් උන්ගේ නමෙ ඉඳන් බොරුව
Nikamata බලාන්න imoji වාල තත්ත්වය ඇක විතරක්
ඇපල් එකක් එක්ක ඇන්ඩ්‍රොයිඩ් එකක් පාවිචිචි කරන එවුන් දන්නවා ඇපල් වල තියෙන qulity එක... දුකට කවි සීපද කඅයන්න ටපැ බම්
Samsung සංදර්ශකය තමා හොදම කියලා හිතං ඉදියෙ නිකන්ම කොලපාට ඉරක් දර්ශකය එකෙ මතුවෙනකං ඇපල් & samsung හරියට UNP එකයි SLPP එකයි වගේ
ඩුකා හිතෙනා - l wouldn't be able to leave. කියන්නා - මොකක්ද? අපප හැන ගණකා ඩිලා ගත්තෙ
හැම පාරම අලුත් නමක්
ඒත් බලපන්කො මැක් බුක් රෙටින වල වීඩියෝ කොලිටිය
උඹ එක්ක බෑ විකී
හැබැයි ඇස් දෙකට මාර විදියට සැහැල්ලුයි ඇපල් ඩිස්ප්ලේ එක.... මට ඒ කොලිටිය තියෙන වෙන මොනිටරයක් කියන්න පීසී එකට ගන්න. ඇස් රිදෙනව අනික් ඒවයෙ. ඒකයි
අන්න ඒකයි
මම භාවිතය කරන්නෙ macbook එකක්. සංදර්ශකය එක හොදයි ඇත්තටම
අනිත් දවසෙ ඇපල් සමගාම උබෙන් අහල කරන දෙයක් කරයි..
මෙ ලෝකෙතියෙන්නෙ අයින්ෆෝන් විතරයි කියල කියන සුදු තාත්තිලට ඔයිටවඩා දෙයක්න්තේරුම් කරල වැඩ්ක් නැ
ලොලී
ඇපල් උබල හිතන තරම් සුපිරි නෑ බං Asus රොජර් / Pixel වගෙ ඒවත් මේ ලෝකෙ තියෙනව තව ඊටත් වඩා සුපිරි ලේබලය තියෙනව වැඩිය ෆේමස් නැති ටිපර් වෙන්න එපා
අනේ අම්මෝහ් ඒක... අනිත් කම්පැනි අලුත් තාක්ෂණය හොයාගද්දි ඇපල් ලා ඒවට අලුත් නම් හොයාගන්නවා..
වහල්ලු පව් යකෝ.. ඔහොම කියන්න එපා..
කුප්ප ඇපල්
මැගී ඇපල් ඌනා න්ම හොඩ වෙන්නේ් - Okay. මොනව කිව්වත්
හැ
අමො කවුද බන් USA සුපිරි භාන්ඩ වලට වඩා චීන්,කොරියන් ඒවා හොදයි කියලා නිදර්ශනය කරන්නෙ
3D අල්ලන්න mmmm
කවුරැ මොනවා කිව්වත් තමන්ගේ නමක් හදාගත්තම මොන දේ කරත් ඒක බ්‍රෑන්ඩ් එකක්
ඇපලුත් හරියට නිකන්...............................
ඇපල් පෑන්ලගෙ උදහසට ලක්වෙන්නෙපා
ගොඩක ඇපල් usersla කිසිවක් නැත තාක් ෂණික egello සමහරු රාම් ඇක්–ඇක් ennet නොආහා kiyalai විශ්වාස කරන්න කරන්නේ් ලොලී
එ උනාට කැමරාවට ඇපල් කොපිකොරාට සමකොරන්න බැනෙ
ගොබ්බයො තමා ඔව්වා ගන්නෙ
අනේ නිකං පලයං බං යන්න
හරියටම දැනුවත් වෙලාද කියන්නෙ.වීඩියෝ එක වයිරල් කරන්න ගත්ත ඔප්ශන් එකක් නෙවෙයිනෙ
මචෝ දන්නවනම් කියපන්කෝ. Iphone එකේ ඉන්ග්ලිශ් හඬ වර් ගය එක වගේ සිංහල හඬ වර් ගය එක හදා ගන්න බැරිද
රූටනය කියන්නේ ඇපල් වෙළඳසැල් නම එකක් කියන එක හරි. හැබැයි තිරය දර්ශකය තමා හොදම කියන එක මිනිස්සු හදා ගත්ත ඒවා. ඒකට ඇපල් කොම්පැණිය පලි නෑ.
Samsung බොරු හඳ විශේෂාංගය ඇක ගණා මොක්ද hithanne?
ඇපල් බ්‍රන්ඩ් එකක් කියල හිතන් ඉන්න අයට මෙව බොරු කතා
ඇපල් පාවිච්චි කරාන උංට ඔව පේනනල wadakk - Okay. බඞ උංට එච්චර molayakk - Okay.
පොඩ්ඩක් දුක හිතෙනව බං යූසර් ලා ගැන
කුළ corry guys...
මගෙනම් අදහස ඕක ලොකු ගණුදෙනුව එකක් නෙවෙයි
ගෑනු බාගේ මොකත මෙතන කොරන්නෙ
ගෑනු බාගේ මොකත මෙතන කොරන්නෙ(2)
බිලියනයක් $ ව් යාපෘතිය ඒකාට මක්කද අයියේ වුනී
අවුලක් නෑ ෆෝන් එක හොදයි. මේක රෙකෝර්ඩ් කරෙත් iphone එකකින්
i ඉතින් ඩුකා hithenneenjoy your දුරකථනය bro.andorid ශෛලිය iphone වේාව me ඕකකොම යළුවො malli.end of the දවස අහිංසක ආඅපි ටහම andenne
ආඩේ ආව් කොල පටා ඉරා ඈවිල්ල antimat නයිල් මගේ පුතාට වෙල‍ා nawathune ඔක්කෝටම බදූ
එහමෙ ටහම කායන්නේ වෙන්නේ් අතුරුබිඳ - මට නම් එහෙම නෑ. කලාපය කායල ඇණෙන ආඅපි rawatemu
ඇක අන්තර්ජාල wqla කලාපය ඇක්–ඇක් කියළ kiyanne... ලාංකාවේ මඑක නිදහස් ප් රතිසංස්කරණය කරණවාද දාාන්න මාර්තා රටාවල වාල ඒහැම කරාල තිබ්බ
මම පාවිච්චි කරන්නෙත් iphone එකක් මචන්
ඔයාත් ඇපල් එකා අන්තර්ජාල මධ් ය පරාසය compair කරාන ekkenekd
මෝඩ කතා එපා මේ 2023
නානා මමා අපි කරාන ඇක හොදයි kihalla මිනිහෝ කියන්නා - Okay. ඇපල් අලෙි pukan ඉනෙන - මොකක්ද? ඌරු හොදම ඇපල් කියාන ඇකන් midiyalla
හා හරි අපි අපි කැමති ඇක භාවිතය karagannam.. Thaman භාවිතය කරාන ඇක තමායි හොඩ කියළ හිතාන gon මානසිකත්වයෙන් midiyalla...
i ඇපල් ලොකුද ඌරු හොදම ඇපල් කියාන vahal බවින් midiyalla golbel 4n මාකට් ඇක dihala as අරල balaoan
මම ඇපල් 14 promax and s23 ඇක්–ඇක් භාවිතය කරනාව machan...
ප්ලස් noo
ඒකත් දාන්න ඕනෙ
අවුලක් නෑ මමත් iphone එකකින් මේක කරේ
ඒක මිසක්
ඔව් ප් රධාන වෙළඳ භාණ්ඩය Samsung, හැබැයි තව කීපයක් ඉන්නවා LG වගේ
Samsung ,LG
ප් රධාන හේතුව ඇක ඉල්ලූම ධාවකය හිංදා ඒගොල්ලන්ට taniyen සංදර්ශකය නිෂ්පාදනය කරනනා බ
Habai ඒගොල්ලෝ ඩීනා වැඩි තත්ත්වය වාලට gahanne.Dan ඇපල් ඒගොල්ලොම දර්ශකය ගහන්නා සැලසුම කරනෙ yanawa.
විදුලි පහන් හිල = ද්විතියික දුපත
වල එක ෆෝන් එකකට එක අල්ලන්න id එකයි
හැබැයි ඔය හැම කොටස් එකකම විශේෂත්වයක් තියෙනවා. හිටපු අතුරුබිඳ එකක Fringerprint එක තවත් ඒ වර්ගෙම අන්තර්ජාල ෆොන් එකකට සකසන්න කරල භාවිතය කරන්න පුලුවන්. But ඇපල්
නෝඩා වෝව් මීළඟ Wiky ගන්න සටහන
මීවා න්ම අතත
சூப்பர் ப்ரோ
ඔයා පට්ටම චරිතයක් මලයා.බුදු සරණයි.
වාව්. Allah will ආශිර්වාද u සුරකින්න doing what you do
habibi your මට්ටම
@Jayanindu සර්ට් එක
where are you from???
බීරො ගන්න ආදරය from Bangladesh my පලමු නිදර්ශනය පිළිතුර අනේ
අර නකි ගැනි වගෙද මෙ අයියාගේ වැඩ
ඔයාට කවදාවත් වරදින්න එපා ඔතනින් නවතින එපා තව තවත් ඉස්සරහට යන්න ඔයාට හරියන්න ඔනේ
කරන හැම වැඩක්ම සාර්ථක වෙන්න ඕනේ
හැමදේම හිතට පතන විඩිහට ලැබේවා අයියෙ . ඔයා චරිතයක්
ඒ උයන කෑම කන්න ආසයි....
තනිකරම පිස්සුවක් බන් අයියෙ උබ
අර අපෙ අම්මා වගෙනම් දුශ්ට වෙන්න එපා අයියා කවදාවත්ම.හැමදාම හරි යන්න ඕනෙ බුදු සරණයි
මැයි උතුමාණෙනි Buddha ආශිර්වාද you
Heroes කවදාවත් නෑ මරණය
අඩො උබ එදා ඉදපු තැන දැක්කම දැන් පට්ට දැන් උබ චරිතයක් දැන් සමරමු
අඩෝ අයියේ ඔයානම් මාරම චරිතයක්
චරිතයක් එච්චරයි
හැමදාම ඉස්සරහටත් දියුනු වෙන්න පුළුවන් අයියා ඔය වගේ වැඩ කලහම
පටෝටිය තත්ත්වය චරිතයක්
Can’t ඉන්න for you to ලබා ගැනීම more and more…! Congratulations Charith aiyeh…!
කෝම්ද ගැම්ම
vere මට්ටම බීරො
රියල් චරිතයක්..බුදු සරනයි!වැඩ ටික පරිස්සමෙන් හොදට කරගෙන යන්න.
ගොඩාක් පින් බුදු සරණයි
ආණේ matathkannq මොනවාහරි oniirice ඇක්–ඇක්
සුපිරි අයියේ . පුලුවන් විදියට කන්න නැති අයටත් උදව් කරන්න. සල්ලි තිබුනනම් මාත් කරන්න ආසම දෙයක් තමයි නැති අයට දෙන එක .
ගෞරවය
හොද වැඩක් පුතා .....
සුපිරියක්
Waradinne නොආහා කවදාවත්
Fav
නියමයි අයියේ
හදවතින්ම ආදරෙයි එච්චරයි
වැඩි වැඩියෙන් ලැබෙන්න ඕන
ගෞරවය Bro.... උපරිම විශේස
හොඳයි රස්සාව බීරො
තව තවත් ඉදිරියට යන්න ලැබේවා!
This is the වෙනස than others..
මෙන්න බ්‍රෑන්ඩ්
සිත්ගන්නාසුළුයි dishes
හොඳයි රස්සාව
Allah ආශීර්වාදය you සුරකින්න it up
වචනයක්වත් කතා නැතුව නිහඩ ගමනක් ගියා මරුමරු ආඩම්බරයි අයියේ
ගොඩක් පිං ලොක්කා ඔයාලට......
හොඳයි mallioya
congratulations දෙවියෝ ආශිර්වාද you සුරකින්න ගල් කැට
තේරුවන් සරණයි ඔබ ඇතුලු සියලුම දේනාට
habibi
ඔයගෙ ගීතය ඒකාට තත්ත්වය ඕකකොම තරගය වෙනාව ලස්සනයි අයියේ ගෑම්මක් ටහම
At the end… හදවත අල්ලනවා
Fav බීරො
හොඳයි ආශිර්වාද you බීරො
Sema යහ්
খুব ভাল
ගෑම්මක් අයියා ඔයානම්
පට්ට චරිතයක්
පට්ට අයියේ ඔයා නම් සුපිරි චරිතයක් නේ
බුදු සරණයි අයියෙ සුපිරි වැඩක්
සුපිරි
සුපිරි...
Allah ආශිර්වාද you සදහටම
දෙවියනේ ආශිර්වාද you. හොඳයි හොයමින් chef!
හොඳයි රස්සාව බුදුසරණයි
ආහාර cooked with love, හොඳයි අවසන්
දෙවියනේ ආශිර්වාද you more and more
Supiri Lassanai
උපරිම of වාසනාව ඇත්තටම you are the උපරිම
දෙවියෝ ආශිර්වාද you
Up up up
congratulations බීරො
බුදු සරණයි ඔයාට
ඇත්තටම Inspiring!!!!!
සුපිරියි අයියේ
බොහෝ ම පින් මල්ලී....
නියමයි රස්සාව aiya.
@Wild පොත කොල්ලො පොඩ්ඩක් පාර්සල් කරල එවනවකො.Good වාසනාව සහෝදරයා. ලංකාවෙ ඉදලා ඔහොම හරි ගොඩගියාට.
නියමයි වැඩ අයියො
amazing. . සුරකින්න ùp the හොඳයි වැඩ
සුපර් Ayye! You are the උපරිම කෝකියෙක් in the ලෝකය
dakunae gaemma
Congratulations Malli හොඳයි වැඩ with හොඳයි .
ගැම්මක් තමා
සුරකින්න it up පුත
නියමයි!
a දෙවාල් තමයි ඔයට ඔ්‍යා හරියන්නැ
තෙරුවන් සරණයි
නියමයි
මීටත්වැඩිය ඉතිම් මොනාද...තෙරුවන්සරණයි අයියේ...
සුපර්
මේ වාගේ මනුස්සයන්ට තමා හරී යන්න ඔනා
හොඳයි. done.. බීරො සුරකින්න දිදුලන
සුපිරි
Malli ඔ්‍යා පටෝටිය
වානරයා ammagei charithgei තියෙණ වෙනස
තව තවත් හරියන්නෝනි උතුරන්න
නියමයි වැඩ
නියමයි වැඩ
නියමයි මල්ලි...
අපිව සංවේදි කරන්න පුලුවන් වෝයිස් එක්ක
හැකියාවන් තවත් දියුණු වේවා පුතේ..
සිරාවට ඇග හිරිවැටුනා මලයෝ වැඩි ආදරය
මහා රුකක මුල් අංකුරයක් පේනවා මට මේ කොල්ලගෙන්..
eeknm මරු
නියමයි
youtube එස නම ඇක කොහොමඩ
Woow
හඬ
ඇගෙන්ම එන වොයිස් කොහොම වුනත් සුපිරී!
ඇග නම් හිරි වැටිලා ගියා
බාචි අයියාව මතක් උනා මට නම්...
බුදුසරණ යි පත්තිනි මෑණියන්ගේ පිහිට යි පුතා ජයවේවා
ඒක නම් මරු
තෙරුවන් සරණයි පුතේ .ජයවේවා ..
ටී එකේ බලනකොටම ඇග හිරි වැටුනා ඒයි
දුන්නා ආයෙ ඇඬෙන්නම... කොල්ලා පට්ටම දස්සයෙක්
ලස්සන හඬ
කොල්ලො නියමයි
සුපර් හඬ
සිරාවටම හිරිකටු පිපුනා ඈ
මල්ලිය උබට budusarai බඞ ඊඊ - ම්ම්ම්. vasanavannai පරිස්සමින් ගමනා යාගන් jayaveva
හඬ එකහ
පුදුම ලස්සනක්
Wow...
සිරාවට ඇක supiriyak
අම්පාරේ කොල්ලෙක් පොඩ්ඩා
woah‍
මල්එලි
වොයිස් නම් වොයිස් වේරියේශන්ස් නම් වේරියේශන්ස්.. මීළඟ මට්ටම ක් රියාකාරිත්වය .Keep It Up පුතා ..
Wooow සුපර්
අනේ
Woah
වාව් බුදුසරනයි පැට්ටෝ
waahh
සිංදුව පටන් ගද්දි ඇග හිරිවැටුනා
කොල්ලා ලස්සන වෙනව ලොකු වෙද්දි තව
ලස්සනයි පුතේ බුදු සරණයි
හඬ එක සුපිරි
Brooo Pitches
bachi වෝ මතකේ ඌනා
Admin sithale ඩේ
බුදූ සරනයි jayawawa
වැඩි සටහන අල්ලන්න කරාන vidiya...ammoo
හොදයි ලස්සනයි
හඬ
සුපර් හඬ
nan
වාව්
හඬ
නියමයි
සුපිරි
ලස්සනයි පුතේ බුදු සරණයි
සුපිරි
බුදුසරණයි
සම්පූර්ණ ඇක දැනෙණ බහේද
වාව්
ජය පුතා
බුදුසරණයි පුතේ ජයවේවා
ලස්සනයි මල්ලි ෙයා්
‍
මාරම කොලට් වෝයිස් එක්ක පිහිටල තියෙන්නේ තෙරැවන් සරණයි
පුතේ ලස්සනයි සුන්දරයි ,ඔබේ අනාගතය සර්තක වේවා කියා ප්‍රාර්ථනා කරමි ,ශ්‍රී ලංකාවේ මෙතෙක් කල් මා බලපු රියෙලිට් වලින් නම්බර් වන් වොයිස් එකක් ,
පොඩියට පහතරට අඩියකුත් දානවා පොඩ්ඩා මරු ඔහොම ඉදිරියට යමු පුතා
මරු
බුදුසරනයි jayawewaaa
මන් ආසම චුටි ගායකයා බුදුසරණයි ජයවේවා
ඕ
එයානම් ෂෝයි
බුදූ සරනයි පුත ඔයට
බුදු සරණයි
හරිම ලස්සනයි පුතේ තෙරුවන් සරණයි ඔයාට මං දැක්ක දක්ෂතම දරුවෙක් ඔයා ජය වේවා
මාරයි. ක් රියාකාරිත්වය
ගොඩක් ලස්සන ගායනයක් පුතේ බුදු සරණයි
ගොඩක් ලස්සන ගායනයක් පුතේ බුදු සරණයි
සුභ අනාගතයක් පුතේ
බුදුසරණයි මල්ලි
සුපිරියි.....
තෙරුවන් සරණයි පුතේ...
Budu සරනයි පුතැ
බුදු සරණයි මැනික
තෙරුවන් සරණයි පුතේ..!!
බුදුසරණයි මැනික
බුදුසරනයි
බුදු සරනයි
ලස්සන
තෙරුවන් සරණයි පුතෙ
තෙරුවන් සරණයි පුතා
බුදු සරණයි පුතේ
තෙරුවන් සරණයි පුතේ
අම්මො ලස්සනයි
නියමයි so ලස්සන සින්දුව ,this බබා same ඉන්දියා ,super සින්දුව කණ්ඩායම ,will proud of you ද් රෝහියා ලස්සනයි හිරු ,thanks මොහොමඩ් ඉර්ෆාන් මාමේ සෞදි අරාබිය රඑි
බුදු සරණයි පුතේ
දක්ෂයෙක්
ගොඩක සරයක් බලූවා - මොකක්ද? වන්නම - Okay. බුදූ සරනයි
waaw මානිකා
ලස්සනයි පුතට ජයවෙව
හොඳයි රස්සාව මල්එලි හොඳයි වාසනාව for your අනාගතය
වාව්
වාව්.
Lassanai රත්තරනා puthey
@
අනේ ඇත්තටම මෙහෙමත් මනුස්සයො උඩ දැකපු ලස්සනම ලස්සන කමෙඩ් දෙක මරු මෙහෙමත් අපහාස කරන්න හිතක් එනවද ඔයා ගොඩාක් ලස්සනයි දුවේ තව සින්දු කියන්න අපි අහනව හොදේ
හරිම ලස්සනයි
@shona_97 ඔ්‍යා වාසිය
අමුතුම ලස්සනක් තියෙනව ඒ කටහඩේ
ඒ වෝයිස් එකහට පරන මතක අවුස්සනවා
සුපර් හඬ
මට නුබ විතරක් උනාට නුබට ඉන්නෙ මං විතරද.
ලස්සනයි ලස්සනයි ලස්සනයි
ලස්සනයි ලස්සනයි ගොඩක් ලස්සනයි
හරිම ලස්සන හඩක්
හඬ එකහ්
ලස්සනයි
හෙයා ලිප් එකක් නේද
ඇත්තටම එයා ලස්සනයි . විහින් කැත වෙන්නෙ..... කටහඩත් හරි ලස්සනයි .
ලස්සනයි ලස්සනයි බුදුසරණයි මැණික
නම
හරිම ලස්සනයි
Niyamai
හරිම ලස්සනයි අනේ
ලස්සනයි
ලස්සනයි රත්තරනා
ලස්සනයි
තව ටිකක් හැඥීමෙන් කිව්වනම් මරු කියලා හිතුනා
ශ් රී ලංකා ලංකන් rihanna
ලස්සනයි
ලස්සනයි
ලස්සනයි
හරිමා ලස්සණ
woooow..
හරිම ලස්සනයි
wooow.harima.lasani.
wow!
Woooow හරිමා ලස්සනයි
විශේෂ ma කෙල්ල
හරිම ලස්සනයි බුදු සරණයි වස්තුව
@
[cute]
ටැමිල් කොල්ලෙක් නෙද ?
එකහ් සුපිරි වෝයිස් එක්ක
අහින්සක ලස්සනක් තියෙන්නෙ
අඩෝ ලස්සනට කියන්වා ඕයි
Sirasata adareihiru වාසිය වැනෙනා එප
සදුන්ගෙ ආසම සින්දුවක්
හරි යන්න ඔිනා හැම එකෙක්ට ම අහිංසක හීන වලට
අඩේ මම හිතුවේ අවුරුදු කුමාරයෙක් කියලා
ලස්සනට කියනවා කොල්ලා හැබැයි
අහිංසක කොල්ලෙක්
අහිංසක කොල්ලෙක්
මතක තියාගන්න the දිනය
ලස්සනයී
ලස්සනයි ඒක නියමෙට කියනව..
අඩෝ ඒක පට්ට
උපරිම
ලස්සන වොයිස් එකක්
මීළඟ මට්ටම
දෙමල කොල්ලෙක් සින්හල සින්දුවක් ලස්සනට කියනවා...
හිරු එස උංට වාඩා හොද
දැනුත් ඒක අහන්න වෙලා
That ගීතය
පලමු නිදර්ශනය
@Sithum Nadeeshan ටික්කෝ ඔයාත් වෙගී
ඉස්ස්ර ගියේ් සුපර් තාරකාවක් - ඔව්. පටන ගණනැ නොදඩා ‍
ලස්සනයි සුපිරි
shaa සිංදුවේ චොරා උණේත් මරුවට කියෙනව
Wowed
Eya හාරි siriyawanthay
wawoooo
Tamil නැඩ
වාව්.
ඒකහ
ලස්සනයි ලස්සනයි
නව
උණ්ඩය e ගැමා
පට්ට
Lassanai බඞ හඬ ඇක
Harima Lassanai
Wowww
Wowww
Woah
@Sandun Perera
හරි අහින්සක පිං මූනක්
හොඳයි
මාත් yunw
අදමින් අයිය
Mia කේහුබා කව්ද කියලා දන්නැතුව Google සොයන්න කරල බලපු මම
මීයා කලීෆා
මං වගේ ලස්සනයි නේද
මීයා කන්න වගෙ යන්නෙ
@Dinil Seniru අමෝ ශ් රී ලංකා ලංකන් dramas We can මුරය with පව්ලෙ සැමටම
අත තියනකන් මියා කලීෆ තමා
Mia කලිෆා
අපේ එකෙක්
යකෝ
@kiferkrause510 @Shane පෙරෙරා mia කිෆීර්
මීයා කාෆිය කිව්වානම් ඊට වඩා හොඳයි
මියන්ති කල්හාරි
මියා කලීෆ
ගෙදර මිනිස්සු එක්ක බැලුවනම් හිනා යනවනෙ
දෝනිගෙන් ඈත් වෙලා ඉන්න
මියන්ති කල්හාරි
අර මීයො කන කෙල්ල ගැනද කියන්නෙ
මේ සක්වලේ ඒකී දන්නැති එකෙක් නෑ
කන්නාඩි දාන කෙල්ලෙක්නම් මතකෙට එනවා
I වැටුනා it
I වැටුනා it
යකො
පතුරම්
ඇක අහපු ලස්සණ
මම මේක කලින් දැකලා තියෙනවා
@Sade. ........
දන්නවා
පතුරම්
අම්මෝ...
මියා කේහුබා my කැදලි
මල්ලිගෙ මීයාට dewipihitai
මියා කලිෆා
@මියා කලීෆා මීනී වඩක්
@Mia K. Akke me ඔයාව අහනව
mia ඔයාගෙ නම සිරසෙ teledramas වලත් කියවෙනවා@Mia K.
ගමෙ නම් ඉන්නවා මියො ඔන ද
@SHEHA BBH දන්නවාද
@thejakapremasiri03 @~Themiya_Gimhana~ @Dinol Ransuka @virenzz @Hirusha
@Bandara.. @@.... sithum.....
@saviiii
@saviiii
@S_laWanya
@Thaviru Perera @Gaming With Podiii
@_limirusenanayake @dunith_perera
@E ආර්. A නෝර් D A
@Vizzz
@ @ @shenannnz17 @senukaaaa @Mahiyaaa
@ "
@sergio_ferz
@shehan_
@@ Anja_Boy
@SherAn Sineth
@rithu ඍාතු
@Mia K.
@LEO_ANOX
,
@Dark රාත් රිය
@Itz_randy_k
@Gaming@zxyn @RIMUU .....
@Mia K.
ඒ ඉස්කෝලවලට යන්න බැරි වුන අයට හරීයට රිදිලා
බලාගෙන ඉන්න for ධර්මරාජා Vs kingswood ලොකු තරගය
තරගය of the නිල් is හොඳයි බීරො
මෝනා. ඌණතා මාටා ලස්සණ රාජන්ස් , kinswood ලොකු තරගය ගීතය eka..
ක් රිකට් වලට විතරක් නෙමේ, පාපන්දු ක් රීඩාව වලටත් ඕවගේ ලොකු තැනක් තිබ්බනම් ලංකාව ලොකු තැනකට ඇවිල්ල. ලංකාවෙත් පාපන්දු ක් රීඩාව වලට කැමති ගොඩක් ළමයි ඉන්නවා.
ක් රිකට් වලට විතරක් නෙමේ, පාපන්දු ක් රීඩාව වලටත් ඕවගේ ලොකු තැනක් තිබ්බනම් ලංකාව ලොකු තැනකට ඇවිල්ල. ලංකාවෙත් පාපන්දු ක් රීඩාව වලට කැමති ගොඩක් ළමයි ඉන්නවා.
මහනාම ලගදිම බලාගනන
Royl
අපේ ඉස්කෝලෙට ඇරෙන්න මන් සපෝර්ට් කරන එකම ඉස්කෝලේ අනාන්දේ තමා ඒකට හේතුවක් තියේ හේතුව අහන්න එපා හැබැයි මගේ ඉස්කොලෙත් අහන්න එපා
@@avii__‍ තරගය බලන්නෑ යමුද
ගොඩක් අයට රිදිලා.
Legends කවදාවත් නෑ මරණය තියන්න යනවා Maroons
SPCSJC
ඕකකොම ඔක්කෝටම නියමයි bn.meka විතරක් නෙමේ
ක් රීඩාව අයිති කොළඹට විතරක් නෙවේ.පරිපාලනයේ වැරදි නිසා කොළඹ විතරනෙ cricketers ලා ඉන්නවා කියලා හිතන් ඉන්නෙ නම ගියපු ක්‍රීඩකයො දෙන්නෙක් තුන්දෙනෙක් බිහි උනා කියලා ලංකාවෙ ක්‍රිකට් අදින්න කොළඹට දැන් බෑ.
Wales සැබ
තරගය of the නිල්
KEGALLE ran මලා සටනත් ඔහෝම දාන්නකො evath හොදයි
it.s not a පාසැල it.s my 1st විශ්වවිද් යාලයේ නාලන්ද ,, proud to be a nalandian
RICHMOND Vs MAHINDA ලොකු තරගය Galle ලගදීම..
මෝනා. ayyh මෝනා කිව්වත් මඑක තමයි බඞ ලොකු තරගය ඇක
Proud to be a Nalandian
යුද්ධය of the Maroons NC
anandiyan ක් රිකට්
පව් අනේ ගොඩක් උන්ට රිදිලා වගේ ගොඩක්
ඕවා හොදයි ගමටත් ගියානම් තවත් මරු
maroons
මේක තමා ලොකු තරගය එක... BBM 94...
මේක තමා ලොකු තරගය එක... BBM 94...
ඉන්න රිච්මන්ඩ් Vs මහි්න්ද
තරගය of නිල් < තරගය of maroons
අන්දර් ...Nalanda......Gothami
සුලෝහිත සංග්‍රාමය
Nalanda comenn
ඇනා
අන්දර්
Nalanda
ඒහැම ඇක්–ඇක් හොදයි කියාන ඇක හාරි - Okay. නැඩ බීරො ඕකකොම සෙලලම් කරන්නේ් එකාම කණ්ඩායම එකාටනෙ කවාදා හාරි හොඳයි අවසන් all schools
රාජා thomian
ගැම්මක් තමා ඉතින්
රිච්මන්ඩ් Vs මහි්න්ද තත්පරය
මූලිකවම its සංගීත show.And u ගේන්න නිදහස් of අවස්ථාව to මුරය a තරගය
Shoi ane… - ඔව්. iscole යනඑන තිබ්බානම් කියළ හිතෙනව ස්කූල් නිල ඇඳුම ආදින lamainwa දෑක්කම
දැක්කේ නැහැ වගේ යන්න ඕනි
apeh ලොකු තරගය එකහ
Mahanama බලන්නකෝ
Mmm
මීළඟ Rahula Vs Darmapala
AnandaNalanda
ලස්සණ කොලේලො ටිකා ඉතින් ආනන්දේ නාලන්ද
ඒකාට යනා ආයාගේ සතූට
පූ. Vs npc ‍
‍ana
දවස
@Mister Milan Utto හදමුද
තරගය ඇක දිනය අපිත් හිටියා දවසැ දෑකීම හබයේ අදමින් අයියව හම්බඋනේ නොආහා නැැහ kohethe හිටියැ
තරගය ඇක දිනය අපිත් හිටියා දවසැ දෑකීම හබයේ අදමින් අයියව හම්බඋනේ නොආහා නැැහ kohethe හිටියැ
ගීතය එකේ එක තැනක lyrics වල තියෙනව කොළඹ ක්‍රිකට් නිසා ලංකාවෙ ක්‍රිකට් ගොඩ ගියා කියල ලංකාවෙ නෙවේ ලෝකෙම නම ක්‍රිකට් වලින් උස්සල තියන්න පුලුවන් කොලඹට විතරක් නෙවේ ලංකාවෙ හැම තැනටම ක් රිකට් ගිනිච්චන්
රාජකීය thomian
@Lakshana Marasinghe
@Henuka Vithanage
@Nilupul Senavirat910 @vihara @Radin_Rithmaka01 @i
@Thamalu Nayanasith
@Julia Sonali
@Denura Weerasinghe
@Silent_notes
@Senal Nethsara
@ ᥫ᭡
@Methu
හබැයි දැන් කණ්ඩායම එකෙ ඉන්නෙ රිච්මන්ඩ් උන් පව් කොළඹ උන්
@SathiKa කිසිවක් නැත
ශ් රී ලංකා Lanka ක් රීඩාව --> Colombo Schools..
ලොකු තරගය ලොකුද ..? කොළඹ ලොකුද අහන්නෙ ඉතිං ඉරිසියාකාර එවුන් තමයි
පූ. ඉස්කොලෙට me thatveta ගනනා knv ඔටා කට්ටක් ‍
Ds - Mahanama පදිරි ඔ්‍යා ඕකකොම
මැගී acount ඇක අනුගමනය කරාල හරියට ටිකක දාන්නකො
මෝඩයන් ස්මග වද කරන්න බාරි හින්ද නිකං ඉන්න්ව
රාජා ලොකු තරගය ඒකාට oyh ඕකකොම තත්පරය
ලොකුම ලොකු මච් එක මොනා කිඋවත් කට්ටියට ඉරිසියද
විහිලුද මේ
අන්දර්
කණ්ඪය මච් වළටත් me වාසිය m අනුග් රාහක හම්බඋනා අදාල නොවේ මිට වාඩා කට්ටිය ටෙම් ඒකාට හෝඅය ගනනා පුලුවනඈ වේ colabat m නතර වේලා තියෙන නතුව
අඩෙ මං වගෙම තමයි
ඔයාලා මෙහෙම කරගන්න එපා
ගොඩක් හිනාගියා තෑන්ක්ස්
අඩෝ මගේ එකා
@senithiranya07 ඔයටත් මෙහෙමා දැයක ඌනා නැඩ
මං වගේ තව එකෙක් හම්බුනා
@Shehan Madhuranga හය්
@Anuki_ adoh ahibame දැක්කා ඈක් මාතෘකාද
මම නම් පොලිස් ගාන් යන්නෙ
මමth ඇහිබබ දෙකම කපා ගත්තා 3 වසරෙදි
අඩේ මට උනා වගේ . සති දෙකක් ඉස්කෝලෙ ගියෙත් නෑ වැවෙනකම්
මං වගෙ ගොනෙක් ..
මම වගෙ
අත්තෙක් oknm
Mn වගෙ ඩැල් එකක් 9 වසරෙදි මත් ඔම කරා
Same
Me to
හරි සෝක්
පලවෙනි පාර මටත් ඔිකම උනා
මිනිහෝ වෙළුම
අම්මෝ ගොඩක් හිනා ගියා
ගොඩක් ලස්සනයි
මම තුවාල උන විදිහට රු.5 ඩෙටෝල් ප්ලාස්ටර් ගැහුවා මාසයක් විතර
අඩෝ මගේ එකා
ඇති යාන්තන් මන් වගෙ තව එවුන් ඉන්නවනෙ
ඇති යාන්තන් මන් වගෙ තව එවුන් ඉන්නවනෙ
cir ciddii
අයියා
වදුරට දැලිපිහිය හම්බුනා වගේ
උබ මගේ එකා බන් මාත් ඕකම කරා
ඔහොම කරන්න ගිහින් මගෙ යාලුවෙක් නැතිවුනා
කව්ද මූ
මමත් ඔහොම ගියා කලේයක්
අම්මෝ මම් වගෙ
same හේ
Matat ඌනා oka මණ් paticnum එකෙන Adan ගියේ්
same
Adde මිනිහෝ වාගේමයි
@Yushitha Herath kaawada මතකේ උනේ්
මිනිහෝ වාසිය ඇක්–ඇක්
මට හිනාව නවත්ත ගන්න බැනේ මම මඑක
ගොඩක් හිනාගියා ස්තූතියි
ගණිතය කාරා oooka
මාත් ඕම තමයි මුලින්ම
අයියේ
ammo..davse හොදම viluwa
මිනිහෝ හිතුවෙ මණ් vitharay කියළ
same
same
Me too
තලය 2 එකකින් kapaagaththu මමා
මණ් වෙගී සතුටුයි
Mn හිතූවෙ මණ් vithry ඔහෝම ක්රී කියළ
Mn හිතූවෙ මණ් vithry ඔහෝම ක්රී කියළ
ගණිතය okamai කාරෙ
Matath ඔ්‍යා tiaka ටහම e කෙලෙ
ආඩෝ ඔ්‍යා වෙදර් මටාත් වෙල‍ා තාියනවා ඔැි
වානරයා මෝඩ මල්ලිත් ඔ්‍යා වාසිය
යකෝ මිනිහෝ තේරුනාද? ගියේ් sapattuu කලෞ පොලිස් අවලංගු
گردن سبھی ہلاتے ہیں
@Grewon Fernando @ThatOneGuy @ @yasiruuuu
@Sanuuuuu_
@H1math @Hesandu
@Senhas Nanvidu
@ᴘᴀʀᴋ sʜᴇʜɪ
එ අස්සෙ අරු කතරගම මගුලක් කියනවා අමු ගවයා
පතුරම් තත්පරය vagemi ubathe අයියේ
මාත් ඉරක් ගහන්න ගිහින් කැපුනා ඇහිබැමෙන් බාගයක්ම තාමත් සමහර තැන්වල වැවිලා නෑ
වානරයා අයියට ඌනා තත්ති ඇනකොට දාමල් ගගැන හෙටය බයට
මමා හිතූවෙ මමා විතරයි ඒහැම gon වාඩා කාරෙ කියළ
අමෝ අමෝ වකුගඩු දෙකත් ඇබරුනා
ඔලුවෙ ඉරක් ගහන්න ගිහින් චොරවෙලා ගෙදර මිනිස්සු එක්කන් ගිහින් කොන්ඩෙ තට්ටෙගෑවා
මත් ඔය ගොන්කම කරා
මටාත් ඌනා oka මමා kivva අම්මට oluva vaduna කියළ ප්ලාස්ටරය ඇක්–ඇක් alava ගතත
Godak කොලේලො Oya අඑත් දැකීම විදල තියෙනව
මිනිසා වාසිය
ඈත්ත
පොඩි කාලේ තනියෙම කොන්ඩේ පැත්තේන් ඉර ගහන්න ගිහිම් කොන්ඩේ කපා ගත්ත මන් ....
8 වසරෙදි කොන්ඩෙ ශේප් කරගන්න කියල හිතල රේසරෙන් ගෑවා. පළාතක්ම ගිහින්. හැමෝටම කිව්වෙ උඳුගොව්වො කාලා කියල

### load the SinhalaBERTo and created preproccess funtion

In [9]:
import pandas as pd
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch

In [10]:
data.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

In [11]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("keshan/SinhalaBERTo")

In [12]:
tokenizer

RobertaTokenizerFast(name_or_path='keshan/SinhalaBERTo', vocab_size=52000, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	4: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False, special=True),
}

### Analyse the tokenizer

In [13]:
# Vocabulary size
vocab_size = tokenizer.vocab_size
print(f"Vocabulary Size: {vocab_size}")

Vocabulary Size: 52000

In [14]:
# Tokenization example
text = "rashmika වගේ"
tokens = tokenizer.tokenize(text)
print(f"Tokens: {tokens}")

Tokens: ['r', 'ash', 'm', 'ika', 'Ġà·Ģà¶ľ', 'à·ļ']

In [15]:
# Token IDs
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print(f"Token IDs: {token_ids}")

Token IDs: [86, 2698, 81, 4920, 415, 277]

In [16]:
# Decoding token IDs back to text
decoded_text = tokenizer.decode(token_ids)
print(f"Decoded Text: {decoded_text}")

Decoded Text: rashmika වගේ

In [17]:
# Special tokens
special_tokens = tokenizer.special_tokens_map
print(f"Special Tokens: {special_tokens}")

Special Tokens: {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}

In [18]:
# Padding and truncation
encoded_input = tokenizer(text, padding='max_length', truncation=True, max_length=10)
print(f"Encoded Input with Padding and Truncation: {encoded_input}")

Encoded Input with Padding and Truncation: {'input_ids': [0, 86, 2698, 81, 4920, 415, 277, 2, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}

#### [0, 86, 2698, 81, 4920, 415, 277, 2, 1, 1]
0 is typically the ID for the [CLS] token, which is added at the beginning of the input sequence to signify the start of the sequence.
2 is typically the ID for the [SEP] token, which is added at the end of the input sequence to signify the end of the sequence.
1, 1 are padding tokens added to make the total length 10. These are often represented by the ID 1.

#### [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
This mask is used to distinguish between real tokens and padding tokens.
1 indicates that the corresponding token in input_ids is a real token.
0 indicates that the corresponding token in input_ids is a padding token.

In [19]:
# Encoding example
encoded = tokenizer.encode(text)
print(f"Encoded Text: {encoded}")

Encoded Text: [0, 86, 2698, 81, 4920, 415, 277, 2]

In [20]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained("keshan/SinhalaBERTo")
tokenizer = AutoTokenizer.from_pretrained("keshan/SinhalaBERTo")

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at keshan/SinhalaBERTo and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

### Define a function to predict sentiment

In [21]:
# def predict_sentiment(comment):
#     inputs = tokenizer(comment, return_tensors="pt", truncation=True, padding=True)
#     with torch.no_grad():
#         outputs = model(**inputs)
#     logits = outputs.logits
#     predicted_class_id = logits.argmax().item()
#     return model.config.id2label[predicted_class_id]

In [22]:
# # Ensure each comment is passed as a string when applying the function
# data['Predicted Sentiment'] = data['Comment'].astype(str).apply(predict_sentiment)

In [23]:
data.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

In [24]:
# # Compare the predicted sentiment with existing sentiment columns
# data['Business Match'] = data['Business Sentiment'] == data['Predicted Sentiment']
# data['Content Match'] = data['Content Sentiment'] == data['Predicted Sentiment']

In [25]:
# # Print the updated dataset
# data.head(20)

In [26]:
# inspect the label mapping

label_mappings = model.config.id2label
print(label_mappings)

{0: 'LABEL_0', 1: 'LABEL_1'}

In [27]:
def predict_sentiment(comment):
    inputs = tokenizer(comment, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    logits = outputs.logits
    predicted_class_id = logits.argmax().item()
    return predicted_class_id

# positive_sentences = ["ඒක හොඳයි.", "මට හරි සතුටුයි."]
# negative_sentences = ["ඒක නරකයි.", "මට සතුටු නෑ"]

positive_sentences = ["ශුවර්"]
negative_sentences = ["ඒක සුපිරි නෑ.", "ලස්සනයි ඒක"]


for sentence in positive_sentences:
    print(f"Positive sentence: '{sentence}' -> Label: {predict_sentiment(sentence)}")
for sentence in negative_sentences:
    print(f"Negative sentence: '{sentence}' -> Label: {predict_sentiment(sentence)}")

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Positive sentence: 'ශුවර්' -> Label: 0
Negative sentence: 'ඒක සුපිරි නෑ.' -> Label: 0
Negative sentence: 'ලස්සනයි ඒක' -> Label: 0

In [28]:
positive_sentences = ["පුදුමයි.", "ආදරෙයි."]
neutral_sentences = ["මාර වැඩක්.", "එල."]
negative_sentences = ["I hate it.", "This is terrible."]

for sentence in positive_sentences:
    print(f"Positive: '{sentence}' -> Label: {predict_sentiment(sentence)}")

for sentence in neutral_sentences:
    print(f"Neutral: '{sentence}' -> Label: {predict_sentiment(sentence)}")

for sentence in negative_sentences:
    print(f"Negative: '{sentence}' -> Label: {predict_sentiment(sentence)}")

Positive: 'පුදුමයි.' -> Label: 0
Positive: 'ආදරෙයි.' -> Label: 0
Neutral: 'මාර වැඩක්.' -> Label: 0
Neutral: 'එල.' -> Label: 0
Negative: 'I hate it.' -> Label: 0
Negative: 'This is terrible.' -> Label: 0

## Fine tune the model with custom data

In [29]:
pip install transformers datasets torch

Requirement already satisfied: transformers in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (4.42.3)
Requirement already satisfied: datasets in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (2.18.0)
Requirement already satisfied: torch in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (2.2.2)
Requirement already satisfied: filelock in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (3.13.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (0.23.4)
Requirement already satisfied: numpy<2.0,>=1.17 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (1.26.3)
Requirement already satisfied: packaging>=20.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (2023.12.25)
Requirement already satisfied: requests in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (2.31.0)
Requirement already satisfied: safetensors>=0.4.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (0.4.2)
Requirement already satisfied: tokenizers<0.20,>=0.19 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from transformers) (4.66.2)
Requirement already satisfied: pyarrow>=12.0.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (15.0.2)
Requirement already satisfied: pyarrow-hotfix in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (2.1.4)
Requirement already satisfied: xxhash in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.2.0,>=2023.1.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from fsspec[http]<=2024.2.0,>=2023.1.0->datasets) (2024.2.0)
Requirement already satisfied: aiohttp in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from datasets) (3.9.3)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from torch) (4.10.0)
Requirement already satisfied: sympy in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from torch) (3.1.3)
Requirement already satisfied: aiosignal>=1.1.2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from requests->transformers) (2023.11.17)
Requirement already satisfied: colorama in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: mpmath>=0.19 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from sympy->torch) (1.3.0)
Requirement already satisfied: six>=1.5 in d:\uom\l4s1\research\implementation\fyp-research\env\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
data.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

In [31]:
import pandas as pd

# Specify the file path
file_path = "../../data/mnt/sentiment_Aspect_added.xlsx"

# Load the Excel file into a DataFrame
df = pd.read_excel(file_path)

In [32]:
df.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

In [33]:
# Get unique sentiment values in 'Business Sentiment' and 'Content Sentiment'
unique_business_sentiments = data['Business Sentiment'].unique()
unique_content_sentiments = data['Content Sentiment'].unique()

print("Unique Business Sentiments:", unique_business_sentiments)
print("Unique Content Sentiments:", unique_content_sentiments)

Unique Business Sentiments: ['Positive' 'Neutral' 'Negative' nan]
Unique Content Sentiments: ['Positive' 'Neutral' 'Negative' nan 'Negative (Sarcastic criticism)'
 'Negative (could be sarcastic)' 'Negative (Could be sarcastic)'
 'Negative (Comparison)']

In [34]:
# Count the number of NaN values in 'Business Sentiment' and 'Content Sentiment'
nan_business_sentiment = data['Business Sentiment'].isna().sum()
nan_content_sentiment = data['Content Sentiment'].isna().sum()

print("Number of NaN values in Business Sentiment:", nan_business_sentiment)
print("Number of NaN values in Content Sentiment:", nan_content_sentiment)

Number of NaN values in Business Sentiment: 1
Number of NaN values in Content Sentiment: 1

In [35]:


# Sample DataFrame with equal lengths for both columns
data = pd.DataFrame({
    'Business Sentiment': ['Positive', 'Neutral', 'Negative', 'Positive', 'Neutral', 'Negative', 'Neutral', 'Positive'],
    'Content Sentiment': ['Positive', 'Neutral', 'Negative', 'Negative (Sarcastic criticism)', 
                          'Negative (could be sarcastic)', 'Negative (Could be sarcastic)', 
                          'Negative (Comparison)', 'Positive']
})

# Replace specific "Negative" related sentiments with "Negative"
negative_related_sentiments = ['Negative (Sarcastic criticism)', 
                               'Negative (could be sarcastic)', 
                               'Negative (Could be sarcastic)', 
                               'Negative (Comparison)']

data['Content Sentiment'] = data['Content Sentiment'].replace(negative_related_sentiments, 'Negative')

# Drop rows with NaN values in 'Business Sentiment' and 'Content Sentiment'
data = data.dropna(subset=['Business Sentiment', 'Content Sentiment'])

In [36]:
unique_business_sentiments = data['Business Sentiment'].unique()
unique_content_sentiments = data['Content Sentiment'].unique()

print("Unique Business Sentiments:", unique_business_sentiments)
print("Unique Content Sentiments:", unique_content_sentiments)

Unique Business Sentiments: ['Positive' 'Neutral' 'Negative']
Unique Content Sentiments: ['Positive' 'Neutral' 'Negative']

In [37]:
data.head(5)

  Business Sentiment Content Sentiment
0           Positive          Positive
1            Neutral           Neutral
2           Negative          Negative
3           Positive          Negative
4            Neutral          Negative

In [38]:
len(data)

8

In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset

# Load the dataset
file_path = '../../data/mnt/sentiment_Aspect_added.xlsx'
data = pd.read_excel(file_path)

# Ensure all comments are strings
data['Comment'] = data['Comment'].astype(str)

# Split the dataset into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

# Convert pandas dataframes to Hugging Face datasets
train_dataset = Dataset.from_pandas(train_data)
test_dataset = Dataset.from_pandas(test_data)

# Drop the __index_level_0__ column
train_dataset = train_dataset.remove_columns(['__index_level_0__'])
test_dataset = test_dataset.remove_columns(['__index_level_0__'])

# Verify the split
print(f"Training set size: {len(train_dataset)}")
print(f"Testing set size: {len(test_dataset)}")

Training set size: 568
Testing set size: 142

In [40]:
data.head()

,Comment ID,Comment,Business Sentiment,Content Sentiment
0,7.220000e+18,rashmika වගේ,Positive,Positive
1,7.220000e+18,rashmika වෙගේ අඩේ,Positive,Positive
2,7.220000e+18,සාරංග,Neutral,Neutral
3,7.330000e+18,ඉස්සරහට නිලියක් ශුවර්,Positive,Positive
4,7.220000e+18,rashmika මතක් උනා. එයා වගේ ටිකක්,Positive,Positive

 The column __index_level_0__ was likely added when you converted the pandas DataFrame to Hugging Face datasets using the Dataset.from_pandas method.

In [41]:
train_dataset

Dataset({
    features: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment'],
    num_rows: 568
})

In [42]:
test_dataset

Dataset({
    features: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment'],
    num_rows: 142
})

In [43]:
# Print labels for checking
print(f"Train_Dataset: {train_dataset}")
print(f"Ltrain_dataset types: {[type(train_dataset) for train_dataset in train_dataset[0]]}")

Train_Dataset: Dataset({
    features: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment'],
    num_rows: 568
})
Ltrain_dataset types: [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]

the train_dataset and test_dataset are not pandas dataframes. They are instances of the datasets.Dataset class from the Hugging Face datasets library. This class is specifically designed for handling and processing large datasets used in machine learning and natural language processing tasks.

In [44]:
# Print the column names
print("Columns in train_dataset:", train_dataset.column_names)

# Iterate through the dataset and print the values for each column
for column in train_dataset.column_names:
    print(f"\nColumn: {column}")
    print(train_dataset[column][:5])  # Display the first 5 values for brevity

Columns in train_dataset: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment']

Column: Comment ID
[7.35e+18, 7.34e+18, 7.22e+18, 7.21e+18, 7.35e+18]

Column: Comment
['Woah', '@Henuka Vithanage', 'Hayyo සාරංග', 'මම පාවිච්චි කරන්නෙත් iphone එකක් මචන්', 'maroons']

Column: Business Sentiment
['Positive', 'Neutral', 'Negative', 'Neutral', 'Neutral']

Column: Content Sentiment
['Positive', 'Neutral', 'Negative', 'Neutral', 'Neutral']

In [45]:
# # Convert to pandas DataFrame
# train_df = train_dataset.to_pandas()

# # Display the DataFrame
# print(train_df.head())  # View the first few rows

 identify all the unique sentiment values in both the "Business Sentiment" and "Content Sentiment" columns.

In [46]:
# Replace specific "Negative" related sentiments with "Negative"
negative_related_sentiments = ['Negative (Sarcastic criticism)', 
                               'Negative (could be sarcastic)', 
                               'Negative (Could be sarcastic)', 
                               'Negative (Comparison)',
                              'Neutral']

data['Content Sentiment'] = data['Content Sentiment'].replace(negative_related_sentiments, 'Negative')
data['Business Sentiment'] = data['Business Sentiment'].replace(negative_related_sentiments, 'Negative')

# Drop rows with NaN values in 'Business Sentiment' and 'Content Sentiment'
data = data.dropna(subset=['Business Sentiment', 'Content Sentiment'])

# Verify that only the expected sentiments are present
unique_business_sentiments = data['Business Sentiment'].unique()
unique_content_sentiments = data['Content Sentiment'].unique()

print("Unique Business Sentiments:", unique_business_sentiments)
print("Unique Content Sentiments:", unique_content_sentiments)

Unique Business Sentiments: ['Positive' 'Negative']
Unique Content Sentiments: ['Positive' 'Negative']

In [47]:
# Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("keshan/SinhalaBERTo")
model = AutoModelForSequenceClassification.from_pretrained("keshan/SinhalaBERTo", num_labels=2)  # Adjust num_labels if necessary

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at keshan/SinhalaBERTo and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [75]:
from sklearn.model_selection import train_test_split
import numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from datasets import Dataset

sentiment_mapping = {
    "Positive": 1,
    "Negative": 0
}

# Define the preprocessing function for Business Sentiment
def preprocess_business(examples):
    comments = examples['Comment']
    business_sentiment = examples['Business Sentiment']
    
    # Tokenize the inputs
    tokenized_inputs = tokenizer(comments, padding="max_length", truncation=True, max_length=128)
    
    # Convert business sentiment labels to numerical values
    labels = [sentiment_mapping[business] for business in business_sentiment]
    
    # Convert labels to a numpy array for Trainer compatibility
    tokenized_inputs["labels"] = np.array(labels)
    
    return tokenized_inputs

# Define the preprocessing function for Content Sentiment
def preprocess_content(examples):
    comments = examples['Comment']
    content_sentiment = examples['Content Sentiment']
    
    # Tokenize the inputs
    tokenized_inputs = tokenizer(comments, padding="max_length", truncation=True, max_length=128)
    
    # Convert content sentiment labels to numerical values
    labels = [sentiment_mapping[content] for content in content_sentiment]
    
    # Convert labels to a numpy array for Trainer compatibility
    tokenized_inputs["labels"] = np.array(labels)
    
    return tokenized_inputs


# Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("keshan/SinhalaBERTo")
model = AutoModelForSequenceClassification.from_pretrained("keshan/SinhalaBERTo", num_labels=2)  # Adjust num_labels if necessary

# Split the data into training and test sets
train_df, test_df = train_test_split(data, test_size=0.2, random_state=42)

# Convert pandas DataFrames to datasets Dataset
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at keshan/SinhalaBERTo and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [66]:
train_dataset_business

Dataset({
    features: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment', '__index_level_0__', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 567
})

In [67]:
train_dataset_content

(Dataset({
     features: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment', '__index_level_0__', 'input_ids', 'attention_mask', 'labels'],
     num_rows: 567
 }),)

In [68]:
test_dataset_content

(Dataset({
     features: ['Comment ID', 'Comment', 'Business Sentiment', 'Content Sentiment', '__index_level_0__', 'input_ids', 'attention_mask', 'labels'],
     num_rows: 142
 }),)

In [69]:
from transformers import Trainer, TrainingArguments

# Define the training arguments
training_args = TrainingArguments(
    output_dir="./results",          # output directory
    evaluation_strategy="epoch",     # evaluation strategy
    learning_rate=2e-5,              # learning rate
    per_device_train_batch_size=16,  # batch size for training
    per_device_eval_batch_size=16,   # batch size for evaluation
    num_train_epochs=3,              # number of training epochs
    weight_decay=0.01,               # strength of weight decay
)

In [70]:
# Define the compute_metrics function for evaluation
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    # Assuming binary classification for simplicity
    accuracy = (preds == labels).mean()
    return {"accuracy": accuracy}

In [77]:
# from transformers import default_data_collator

# Initialize the Trainer for Content Sentiment
trainer_content = Trainer(
    model=model,                         # the model to be trained
    args=training_args,                  # training arguments
    train_dataset=train_dataset.map(preprocess_content, batched=True),   # training dataset with preprocessing
    eval_dataset=test_dataset.map(preprocess_content, batched=True),      # evaluation dataset with preprocessing
    compute_metrics=compute_metrics,     # evaluation metrics
)

# Fine-tune the model for Business Sentiment
trainer_content.train()

Map:   0%|          | 0/567 [00:00<?, ? examples/s]

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

TrainOutput(global_step=108, training_loss=0.47586423379403575, metrics={'train_runtime': 642.0593, 'train_samples_per_second': 2.649, 'train_steps_per_second': 0.168, 'total_flos': 56331761278464.0, 'train_loss': 0.47586423379403575, 'epoch': 3.0})

In [79]:
# Initialize the Trainer for Business Sentiment
trainer_business = Trainer(
    model=model,                         # the model to be trained
    args=training_args,                  # training arguments
    train_dataset=train_dataset.map(preprocess_business, batched=True),  # training dataset with preprocessing
    eval_dataset=test_dataset.map(preprocess_business, batched=True),     # evaluation dataset with preprocessing
    compute_metrics=compute_metrics,     # evaluation metrics
)

# Fine-tune the model for Business Sentiment
trainer_business.train()

Map:   0%|          | 0/567 [00:00<?, ? examples/s]

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

TrainOutput(global_step=108, training_loss=0.17344352934095594, metrics={'train_runtime': 647.9758, 'train_samples_per_second': 2.625, 'train_steps_per_second': 0.167, 'total_flos': 56331761278464.0, 'train_loss': 0.17344352934095594, 'epoch': 3.0})

In [81]:
# Save the model
trainer_content.save_model("./results_content")
trainer_business.save_model("./results_business")